// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nyhbeyurlejwfgreyzoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55aGJleXVybGVqd2ZncmV5em9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNTk3MDMsImV4cCI6MjA2NzYzNTcwM30.cNG_-RLChJmWMOtFeh8B_YMrPmdsfavKwolTV7xIYXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});